// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6b4VIg6onL0OYnvUqhyhLAyfvoljKjDY',
    appId: '1:144787903889:web:d3d02203efab7779ab3630',
    messagingSenderId: '144787903889',
    projectId: 'stash-1c137',
    authDomain: 'stash-1c137.firebaseapp.com',
    storageBucket: 'stash-1c137.firebasestorage.app',
    measurementId: 'G-NVBHNKPK6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEqtjay-KI7Cj_XDB7CajxM94-eiR7Ils',
    appId: '1:144787903889:android:d3d921489b9d3dcfab3630',
    messagingSenderId: '144787903889',
    projectId: 'stash-1c137',
    storageBucket: 'stash-1c137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb3jOE9cs1o22NkSA9sK94tz2A7wraV6g',
    appId: '1:144787903889:ios:321b401a86d828c2ab3630',
    messagingSenderId: '144787903889',
    projectId: 'stash-1c137',
    storageBucket: 'stash-1c137.firebasestorage.app',
    iosBundleId: 'com.stevie.stash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb3jOE9cs1o22NkSA9sK94tz2A7wraV6g',
    appId: '1:144787903889:ios:325131f9bde359feab3630',
    messagingSenderId: '144787903889',
    projectId: 'stash-1c137',
    storageBucket: 'stash-1c137.firebasestorage.app',
    iosBundleId: 'com.example.stash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6b4VIg6onL0OYnvUqhyhLAyfvoljKjDY',
    appId: '1:144787903889:web:6c2115bf442e4e33ab3630',
    messagingSenderId: '144787903889',
    projectId: 'stash-1c137',
    authDomain: 'stash-1c137.firebaseapp.com',
    storageBucket: 'stash-1c137.firebasestorage.app',
    measurementId: 'G-PKKMQRHX72',
  );

}